####
set -g @larrow ""
set -g @rarrow ""

set -g @BG "#[fg=#df8e1d,bg=default]"
set -g @FG "#[fg=#e6e9ef,bg=#df8e1d]"
set -g @ABG "#[fg=#40a02b,bg=default]"
set -g @AFG "#[fg=#e6e9ef,bg=#40a02b]"

bind r source-file ~/.config/tmux/tmux.conf \; display-message " Config Reloaded! "

set -g default-terminal "tmux-256color"

set -g history-limit 10000
set -g mouse on

set -g status on
set -g status-interval 1
set -g status-position "bottom"
set -g status-style "default"

set -g status-left-style "default"
set -g status-left-length 100
set -g status-left "#{@BG}#{@larrow}#{@FG} #S #{@BG}#{@rarrow} "

set -g status-right-style "default"
set -g status-right-length 100
set -g status-right "#{@BG}#{@larrow}#{@FG} %H:%M:%S %y-%m-%d #{@BG}#{@rarrow}"

set -g status-justify "left"
set -g window-status-separator " "
set -g window-status-style "default"
set -g window-status-format "#{@BG}#{@larrow}#{@FG} #I:#W#F #{@BG}#{@rarrow}"
set -g window-status-current-style "default"
set -g window-status-current-format "#{@ABG}#{@larrow}#{@AFG} #I:#W#F #{@ABG}#{@rarrow}"

set -g mode-keys vi