################
# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

################
# tmux-resurrect
set -g @resurrect-dir '~/.config/tmux/resurrect'

################
set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @larrow ""
set -g @rarrow ""

set -g @thm_sty1_bg "colour196"
set -g @thm_sty1_fg "colour231"
set -g @thm_sty2_bg "colour248"
set -g @thm_sty2_fg "colour231"

set -gF @thm_arr_sty1 "bg=default,fg=#{@thm_sty1_bg}"
set -gF @thm_txt_sty1 "bg=#{@thm_sty1_bg},fg=#{@thm_sty1_fg}"
set -gF @thm_arr_sty2 "bg=default,fg=#{@thm_sty2_bg}"
set -gF @thm_txt_sty2 "bg=#{@thm_sty2_bg},fg=#{@thm_sty2_fg}"

set -gF @thm_sel_sty1 "bg=colour153,fg=default"

################
set -g prefix "C-b"
set -g default-terminal "screen-256color"
set -g mouse on
set -g base-index 1
set -g renumber-windows on
set -g history-limit 10000

################
bind r source-file ~/.config/tmux/tmux.conf \; \
  display " Config Reloaded! "

################
# https://github.com/tmux/tmux/issues/2225#issuecomment-633121891
set -g status on
set -g status-keys emacs
set -g status-interval 5
set -g status-justify left
set -g status-position bottom
set -g status-style default

set -g status-left-length 100
set -g status-left-style default
set -g status-left "#[#{@thm_arr_sty1}]#{@larrow}#[#{@thm_txt_sty1}] #S #[#{@thm_arr_sty1}]#{@rarrow} "
 
set -g status-right-length 100
set -g status-right-style default
set -g status-right "#[#{@thm_arr_sty1}]#{@larrow}#[#{@thm_txt_sty1}] %H:%M:%S %y-%m-%d #[#{@thm_arr_sty1}]#{@rarrow}"
 
set -g window-status-separator " "
set -g window-status-style default
set -g window-status-format "#[#{@thm_arr_sty2}]#{@larrow}#[#{@thm_txt_sty2}] #I:#W#F #[#{@thm_arr_sty2}]#{@rarrow}"
set -g window-status-current-style default
set -g window-status-current-format "#[#{@thm_arr_sty1}]#{@larrow}#[#{@thm_txt_sty1}] #I:#W#F #[#{@thm_arr_sty1}]#{@rarrow}"
set -g window-status-activity-style default
set -g window-status-bell-style default
set -g window-status-last-style default

################
set -g message-limit 10
set -g message-line 1
set -g message-style "#{@thm_txt_sty1}"
set -g message-command-style default

################
set -g cursor-style default
set -g cursor-colour default

################
set -g mode-keys vi
set -g mode-style "#{@thm_sel_sty1}"
set -g copy-mode-match-style default
set -g copy-mode-current-match-style default

################
set -g menu-selected-style "#{@thm_sel_sty1}"

################
set -g pane-base-index 1
set -g pane-border-lines single
set -g pane-border-style default
set -g pane-active-border-style default

################
run '~/.config/tmux/plugins/tpm/tpm'
