"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
# palette = "dracula"

[palettes.dracula]

[username]
show_always = true
style_root = "bold red"
style_user = 'bold yellow'

[hostname]
ssh_only = false
style =	'bold green'

[direnv]
disabled = false

[shell]
disabled = false
style = 'bold green'
