{{- $fontDir := "" }}
{{- if eq .chezmoi.os "darwin" }}
{{-   $fontDir = "Library/Fonts" }}
{{- else if eq .chezmoi.os "linux" }}
{{-   $fontDir = ".local/share/fonts" }}
{{- else if eq .chezmoi.os "windows" }}
{{-   $fontDir = "AppData/Local/Microsoft/Windows/Fonts" }}
{{- end }}

["{{ $fontDir }}/CascadiaMono"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaMono.zip"
    exact = true
    refreshPeriod = "24h"

["{{ $fontDir }}/Monaspace"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Monaspace.zip"
    exact = true
    refreshPeriod = "24h"